# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  # First job (will run in parralel with 2nd Job)
  weekday_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon
    steps:
      - name: "Hello world when it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Mon' }}
        run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat

  # Second job
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
#         node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        path: my-node-code
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: leojrbk/ci-code
        path: ci-code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo $GITHUB_WORKSPACE
    - run: ls -la
    - run: cat ci-code/src/test-node.sh
    - run: sudo chmod +x ci-code/src/test-node.sh
    - run: sudo ci-code/src/test-node.sh
#     - run: npm run test-arrow
#     - run: npm run test-callback
#     - run: npm run build --if-present

#     - uses: actions/javascript-action@v1
#       with:
#         milliseconds: 1000
